### ISSUE TITLE
DatabaseError: Can't Load Database

### ISSUE THREAD

**Issue by ghost** [Belphemur/node-json-db#103]
const { JsonDB } = require( 'node-json-db' );
const { Config } = require( 'node-json-db/dist/lib/JsonDBConfig' );

var db = new JsonDB(new Config("myDataBase", true, false, '/'));

var data1 = db.getData('/');
console.log(data1);  // **result: {}**

db.push('/db', {}); // **myDataBase.json: {db :{}}**

var data2 = db.getData('/db');
console.log(data2); // **result: DatabaseError: Can't Load Database...**

**Comment by fafamnzm** [comment]
Just to mention, I got the same error out of no where! after deleting the db.json file, it recreated it, and the error went away!
I have no Idea why it happened!

**Comment by carlardron** [comment]
Thought I'd chime in while I was searching: the issue I had was due to deleting all the values out of the document. 

node-json-db expects at least an empty object `{ }` if the file still exists. If is doesn't exist it creates a new file but with an object.

**Comment by Anton-V-K** [comment]
The original code sample doesn't produce any errors with `Node.js 18.12.1` and `node-json-db 2.1.3`.
The output is as follow:
```
...>node Cannot_Load_Database.js
Promise { <pending> }
Promise { <pending> }
```
The created `myDataBase.json` contains the expected data:
```
{"db":{}}
```
Probably the issue had been fixed.

**Comment by techniumOSProjects** [comment]
I'm encountering the same issue and I'm using:
    # node --version
    v18.20.1
    "node-json-db": "^2.3.0",
Perhaps the problem has returned for a round 2?
I let it rebuild the json file, but it always comes out as totally blank, and when I try to put a {} it leaves the file blank, on the next .push() attempt!
