### ISSUE TITLE
I have problems trying to test conditions.

### ISSUE THREAD

**Issue by Bethoth** [Belphemur/node-json-db#105]
Hello!
I'm happy to use `node-json-db` but I have a little annoying problem. I'd like to be able to check if a JSON array is empty or not. I tried a lot of different things such as 
![image](https://user-images.githubusercontent.com/45798269/70834951-ed182200-1dfb-11ea-842c-cc7200ed5c0a.png) but it never works (I need this check)

**Comment by Belphemur** [comment]
if `/prologue/links` is an array, and you're sure of it.

You made a simple mistake.

it's not `links.length()` but `links.length`. For array, the lenght is a property, not a method.
