### ISSUE TITLE
Append to an array?

### ISSUE THREAD

**Issue by praveenbm5** [Belphemur/node-json-db#11]
What if I want to push to an Array? Hypothetical code below!

`db.push("/arraytest/myarray[0]", "0000", true);`
`db.push("/arraytest/myarray[]", "0001", true);`

It will be much easier to simply push to an array than keep track of the array index for every array push!!

I believe this feature would be very easy to implement with minimal code change! Change the regex to accept empty index and simply push to that array when index is empty.

Can you please implement this syntax and feature!

**Comment by Belphemur** [comment]
It shouldn't be hard to do and a nice improvement.

I'll implement it asap
