### ISSUE TITLE
Update node-mkdirp

### ISSUE THREAD

**Issue by ggtylerr** [Belphemur/node-json-db#128]
The version used (~1.0.4) [uses a vulnerable version of minimist.](https://github.com/substack/node-mkdirp/issues/166) Please update to [the latest version from this repo](https://github.com/isaacs/node-mkdirp) (the previous one used has abandoned for a while now.)

**Comment by Belphemur** [comment]
The version 1.0.4 never relied on minimist. I was only the version 0.5.1x (which is abandoned).
