### ISSUE TITLE
getIndex on array

### ISSUE THREAD

**Issue by BNO79** [Belphemur/node-json-db#131]
I've a "table" called "CONFIG" with an array "VAL", the "push" code is the following..

**myObj["nome"] = nome.toLowerCase();**
**myObj["valore"] = valore;**
**myObj["ultima_modifica"] = jsonDate;**
**myObj["id_utenti"] = id_utenti;**
**db.push("/CONFIG/VAL[]", { obj : myObj }, true);**

..but I can't use "getIndex" like describe in documentation, to retrive a specific value into the array, I've try this code..

**let myIndex = db.getIndex("/CONFIG/VAL", pnome, "nome");**

..but doesn't work!

**Comment by git-no** [comment]
me either - `db.getIndex("path","objAttributeName","objAttributeValue")`does not find the index within the array of objects.

**Comment by Belphemur** [comment]
I've updated the documentation in the code and in the readme.
#### Get Index in Array
```javascript

// You can have the current index of an object
db.push("/arraytest/myarray", {id: 65464646155, name: "test"}, true);
db.getIndex("/arraytest/myarray", 65464646155);
// By default, the property is 'id'
// You can add another property instead
db.getIndex("/arraytest/myarray", "test", "name");

// It's useful if you want to delete some object
db.delete("/arraytest/myarray[" + db.getIndex("/arraytest/myarray", 65464646155) + "]");
```
