### ISSUE TITLE
TypeError: FS.existsSync is not a function

### ISSUE THREAD

**Issue by faliagas** [Belphemur/node-json-db#135]
I receive the following error when I try to use it with React:
TypeError: FS.existsSync is not a function

Here is my code:
import {JsonDB} from 'node-json-db';
import {Config} from 'node-json-db/dist/lib/JsonDBConfig';

let config = new Config("myDB", true, false, '/');
let db = new JsonDB(config);

**Comment by Belphemur** [comment]
Hello,

node-json-db for now only work with NodeJS.
No support for the browser.
I have an issue open for it with #22
