### ISSUE TITLE
Array with non-numerical index

### ISSUE THREAD

**Issue by Kaos1337** [Belphemur/node-json-db#15]
Hi,
I'm using the version 0.6.5 from npm, and I think that there is an issue with this command:
```db.push("/arraytest/myarray[test]", {obj:'test'}, true);```

it creates this:

```
{
    "arraytest": {
        "myarray": []
    }
}
```

without the index 'test'.

**Comment by Belphemur** [comment]
hello @Kaos1337 

I shouldn't have let this happen. You shouldn't be able to use non-numerical value as array's index. It is now removed in 0.7.0 since JSON.stringify can't translate the array properties.
