### ISSUE TITLE
Accessing DB through file tree

### ISSUE THREAD

**Issue by rdgifford** [Belphemur/node-json-db#17]
As far as I can tell there's no way to access a db through the working directory. So, for example, if you have a nested file you want to access a db (higher in the file tree) from, you're gonna error out:
`const db = new jsonDB("../database.json", true, true);`
Is there a work around, or do I need to tinker?

**Comment by Belphemur** [comment]
Hello @rdgifford ,

I don't really understand what is your exact question?

If you do ``../database.json`` the lib should create the database in the parent of the working directory (if your process have access to it).

**Comment by rdgifford** [comment]
Hey @Belphemur,

You're completely right. My bad. I made a dumb mistake: The file I was testing from had required modules that were creating jsonDBs themselves. Commented the required modules out and this works. Thank you!
