### ISSUE TITLE
What about a async read/write operation?

### ISSUE THREAD

**Issue by Valexr** [Belphemur/node-json-db#171]
What about a async read/write operation?

**Comment by Belphemur** [comment]
The lib wasn't made for Async since at the time it wasn't available in NodeJS (Promise was the only way ... and as we know, that didn't solve the callback hell).

This would require a rewrite and a breaking change of the library :)

**Comment by Valexr** [comment]
Understood… 🤓

**Comment by Belphemur** [comment]
Will be done in V2.0.0
