### ISSUE TITLE
Performance? Scalability?

### ISSUE THREAD

**Issue by rolfen** [Belphemur/node-json-db#18]
Hello,

I'm curious about the performance.

I think that having a database that writes and reads to plain JSON files is a great thing. I don't want to have to install mongdb/couchdb or whatever, with their proprietary binary formats.
JSON is an open and standardized format. I want my data to be decoupled from a particular database platform.

I had a look at the code, and by the preliminary looks of it, it does not seem that much performance or scalability optimization was done, which is my concern here.

Since I am not sure what is happening in the code, I think I'd best ask you about the topic - whether there is some indexing, partial loading or such optimization happening, or is the whole data just loaded in memory? If so, do you have plans to change that in the future?

Thanks!

**Comment by Belphemur** [comment]
Hello @rolfen,

Well performance wise, it's dumping everything in the memory and rewriting the file completely when saving.

It's not really meant to be scalable or even used as a real database, more like a json file wrapper. I use it for small subset of data. It's perfect for managing configuration file, but it's not meant to be used as a real database.

I don't have any plan to make the core functionality other than a simple file wrapper. For this, there is already a lot of other projects with hundred of hours behind them that are doing a better job.

If you're looking for a database JSON and lightweight I'd recommand [NeDB](https://www.npmjs.com/package/nedb)
