### ISSUE TITLE
Exists & Find

### ISSUE THREAD

**Issue by rdgifford** [Belphemur/node-json-db#19]
Hey @Belphemur,

I had trouble querying my json files while working with node-json-db on a project recently. I needed a way to use data from my json db conditionally. I figured out a workaround and finished the project. Now I have a little time to tinker and I was wondering, could I contribute to your repo? I'd like to suggest a 'find' function.
Right now, getData can't be used for conditionals because it returns an error if the requested entry doesn't exist. Instead, a function like 'find' could return null. 'Find' could take an optional argument for a test that would return from the path specified by the first argument. I imagine 'find' could work for objects or arrays without too much trouble. Doing something like this then becomes easy and clean:

```
if(books.find('/shakespeare')){
    var shakespearean_comedies = books.find('/shakespeare', function(book){
        book.genre === 'Comedy'
    }
}
```

What do you think?

**Comment by Belphemur** [comment]
Hello @rdgifford 

The project is Open-source, every contribution is welcome :)

I would rather have 2 functions:
* exits(path)
* find(path,callback)

Feel free to do a pull request with this. Just keep in mind, I try to keep this project as TDD which mean, test first then implementation.

**Comment by Miklet** [comment]
Hi @Belphemur , it's been a while since this issue was created but I would like to help with this one. I am not sure about .find method and I just want to make sure I understood it properly. It should returns specific array/object if it fits condition from callback, am I right?

**Comment by rajeshpanwar** [comment]
Hi,

How can I merge json data and if key already exist, then override that data.

For example I have a record : 
```
{
   name: "one",
   level : 1
   sections : [
      {name : "test", value : "4", level : 2}
   ]
}
```

data to update : 

```
{
 name : "rajesh",
 sections : [
     {name : "panwar", value : 4}
 ]
}
```

Want to get output like : 
```
{
    name: "rajesh",
   level : 1
   sections : [
       {name : "panwar", value : 4}
   ]
}
```
