### ISSUE TITLE
Auto increment

### ISSUE THREAD

**Issue by dominikwilkowski** [Belphemur/node-json-db#2]
Hey there,

I love this and been using it for a while with no problems. One thing I would love to have though is a uniq ID identifying each DB entry. I've been coding this myself but it aint the same ;)

What do you think?

**Comment by Belphemur** [comment]
Hey,

Can you give me a use case for this ? 
I can add a method like *insert* that would use auto-incremented ids

**Comment by dominikwilkowski** [comment]
Well to identify each doc you inserted. In mongo they give you `_id` ObjectID.
Something like that would be great.
