### ISSUE TITLE
merge data error when the data value is null

### ISSUE THREAD

**Issue by KeZhang** [Belphemur/node-json-db#20]
`var JsonDB = require('node-json-db');
var db = new JsonDB("test.json", true, true);

db.push("/data", {a:null}, false);
db.push("/data", {a:"aaaa"}, false);`

then I got the json data
`{
    "data": {
        "a": {
            "0": "a",
            "1": "a",
            "2": "a",
            "3": "a"
        }
    }
}`

**Comment by Belphemur** [comment]
Thanks for the detailed bug report. It's fixed in 0.7.3
