### ISSUE TITLE
database file replaced with empty string

### ISSUE THREAD

**Issue by haynesgt** [Belphemur/node-json-db#24]
sometimes the database file just becomes empty

**Comment by haynesgt** [comment]
my file watcher was restarting the server halfway through a database change

**Comment by akashnimare** [comment]
@haynesgt I'm getting the same error. Do you know what could be the possible reason behind this?

**Comment by haynesgt** [comment]
For me, I think I had a script that restarted the server whenever a file changed. When the database file was being updated, the script would restart the server and corrupt the database
