### ISSUE TITLE
Minified JSON

### ISSUE THREAD

**Issue by rizaumami** [Belphemur/node-json-db#27]
Is there a switch/parameter to save the JSON file in "minified" form?
So, instead of this:
```
{
   "test":"test",
   "json":{
      "test":[
         "test"
      ],
      "important":5
   },
   "new":"cool"
}
```
We get this:
```
{"test":"test","json":{"test":["test"],"important":5},"new":"cool"}
```
If not, I would like to suggest you to add this feature.

**Comment by Belphemur** [comment]
Hello,

The third parameter of the constructor is about that. If true, it set it to "human readable" if false (the default), it will be the minified version.
