### ISSUE TITLE
Database has cache?

### ISSUE THREAD

**Issue by TheOnlyArtz** [Belphemur/node-json-db#29]
Hey there 👋 , I'm using this wonderful module for music system and I realized when I delete an object which contains an array called `queue` and then I will log the data from the queue ('Check if it's not there and catch errors) I saw that it logs the array perfectly and it does not inside the JSON any more.

**Comment by Belphemur** [comment]
Hey,

By default, the lib keeps everything in memory where the "real" database lays.
If you kept the default configuration, every time you modify it, it will also write the JSON file.
