### ISSUE TITLE
db.get Data inside an array

### ISSUE THREAD

**Issue by leongwq** [Belphemur/node-json-db#3]
I have an array which i would like to delete the first index. How do i get to deleting the data?

It seems like db.delete does not accept [0]

**Comment by Belphemur** [comment]
Hi,

The easiest way is to override the array.
First you use the db.get to get the array, remove the index you don't want and then you push with override the array at the same dataPath.

**Comment by Belphemur** [comment]
I decided to add Array Support to the library.
It's available from the version 0.4.1
Please check the README for more information.
