### ISSUE TITLE
Use `fs.createWriteStream`to avoid data loss

### ISSUE THREAD

**Issue by cPhost** [Belphemur/node-json-db#30]
Currently, we use `node-json-db` which called more than once can cause some issues, for this repo this could be problem if we have more than one instance, so if we implement `fs.createWriteStram` we could avoid such problems.

**Comment by Belphemur** [comment]
I strongly advise against use my lib for more than one instance of the same file.

It's really not stable to use it that way and could easily lead a corrupted json file.
