### ISSUE TITLE
Appending to array doesn't seem to work for me

### ISSUE THREAD

**Issue by sebRomeo** [Belphemur/node-json-db#36]
Hi, thanks for such a great library :)

I have tried
`bdd.push('/comments/244[]', data, true)`

But it create that entry in db : `"244[]":{"nom":"anon","content":"blah"}}`...

I have tried with a non-numeric index and it works just fine...
`bdd.push('/comments/aa[]', data, true)` => OK

Sorry, havent made a pull request cause I don't understand exactly how you process the  `[]`

Thanks ;)

**Comment by Belphemur** [comment]
Hello,

The lib only recognize array name that are following the javascript pattern for variable. In other words, it needs to start with a letter, a underscore or $.
