### ISSUE TITLE
Unable to access indexes of nested arrays.

### ISSUE THREAD

**Issue by towilliamstwilio** [Belphemur/node-json-db#417]
My data is formatted in the following manner:

```
schedules: [
[item 1, item 2, item 3],
[item 1, item 2, item3]
]

```
When trying to update any item in either the first or second nested array,  you get the following error:

'Only numerical values accepted for array index'.

This code works to access the outer array, but it's not possible to access the inner arrays:

`scheduleDB.getData('/schedules[1]')`

Code I used for trying to update the third item in the first inner array.

`scheduleDB.push('/schedules[1][2]', 'Inactive', True)`

**Comment by towilliamstwilio** [comment]
Work around is to just overwrite the entire inner array with the same information and only replace the information I want to update, but I'd rather just target the individual item in the nested array.

**Comment by sidblommerswork** [comment]
@Belphemur  I found this repo last night when researching small NodeJS NoSQL type databases.  I found that this implementation was super cool, and will be using it for some small projects.  I took a look through the "issues" section to see if there were any major problems, but didn't find much.  Instead I found a possible feature to add to the project dealing with Nested Arrays.

I spent today walking through the code, and figuring out how this project worked.  I have completed the implementation of allowing the use of nested arrays.  I am working on figuring out how to move the branch I created from the "nested-arrays" branch to the repository to create a PR.

**Comment by Belphemur** [comment]
@sidblommerswork Any contribution is more than welcome :)

I wanted to work on adding this feature, so all I did was making the tests first. I haven't made any other progress since that (so many other projects ^^').

I'll be happy to review your PR for this feature.

The usual way in GitHub is to fork the project, push your change to your fork in your own "nested-arrays" branch then submit a PR for me to review and merge.

**Comment by sidblommerswork** [comment]
Thanks!  I will do that shortly.   Thank you for providing the
information.  :)
