### ISSUE TITLE
FS no longer supported

### ISSUE THREAD

**Issue by Oddisey** [Belphemur/node-json-db#48]
I am, using Angular 6 and I am running into the following error on build:

```
ERROR in my_dir/node_modules/mkdirp/index.js
Module not found: Error: Can't resolve 'fs' in 'my_dir/node_modules/mkdirp'
ERROR in my_dir/node_modules/node-json-db/dist/JsonDB.js
Module not found: Error: Can't resolve 'fs' in 'my_dir/node_modules/node-json-db/dist'
```

The second library that you are importing is `fs`.

`import * as FS from 'fs'`

This library is now not really a library, I guess. It's got an empty page on NPM that says it used to be a codebase, but isn't anymore. Have you experienced this yet, and is there a workaround/fix for this issue? I would love to use this JSON DB lib, because it looks like exactly what I would like, but this is a roadblock for me to use this.

**Comment by Oddisey** [comment]
This was because I am deploying my angular app into a docker container that isn't running node and therefore does not allow for filesystem syncing. My b

**Comment by Belphemur** [comment]
No problem, I'm happy you found the issue :)

**Comment by Nithur-M** [comment]
The same issue happens with Nextjs. How to resolve it?
