### ISSUE TITLE
cant use email as a key for search

### ISSUE THREAD

**Issue by matteo9966** [Belphemur/node-json-db#557]
I get an error if i use an email as a key, it's probably caused by the "." in the email

![image](https://user-images.githubusercontent.com/75813215/221221656-db2877fa-997b-459f-a2e3-96635fddab31.png)

![image](https://user-images.githubusercontent.com/75813215/221221508-2040dccd-cf5d-43bf-a5c9-0a6089902b94.png)

**Comment by Belphemur** [comment]
I'm not sure if there is an issue with the library.
Basically, you're trying to get an entry that isn't present in the file.

What happens if you try with `m@t.logo.com` ?

**Comment by matteo9966** [comment]
hi @Belphemur, i tried again, it works correctly, probably there is something wrong in my code, sorry for bothering you.

Here is my example showing that it works 
![image](https://user-images.githubusercontent.com/75813215/221366713-91eeccc0-47b6-47dc-8ad0-2298f500b165.png)
