### ISSUE TITLE
Add info on using with TypeScript

### ISSUE THREAD

**Issue by mterrel** [Belphemur/node-json-db#56]
We've been using node-json-db in one of our TypeScript projects for a while, so I was excited to see that this project itself got updated to TypeScript! But I initially had trouble upgrading to 0.9. I eventually figured out how to make it work, but thought maybe others could benefit from having some TypeScript-specific instructions in the README.

The two bits of info that I'd suggest making sure are present in the README are:

1. To use node-json-db, in your own TypeScript project, you **MUST** make sure that the you have the `esModuleInterop` compiler option set to `true` in your project's tsconfig.json. Because of the way the .js and .d.ts files in node-json-db are currently generated, node-json-db cannot be used in a project without `esModuleInterop=true`.

2. Then, to use JsonDB from a TypeScript file, you import like this:
```
import JsonDB from "node-json-db";
```
Just that easy. And then the rest of the instructions should work great!

If you'd like me to make a pull request for the README changes, I'm happy to. Just let me know.

Thanks!

**Comment by Belphemur** [comment]
Hello,

Firstly, thanks for the previous PR to add the type into the packages, it's the first time I was using Babel to build a TS lib.

I would love a PR with those instructions for the readme.

**Comment by mterrel** [comment]
No problem! I'll send a PR your way.

And just out of curiosity, why did you choose to go with Babel in addition to TypeScript, rather than just using the TypeScript compiler to generate both the Javascript and the type definitions? I've had to use both when solving certain problems along with Webpack before, but it wasn't immediately obvious what the benefit of Babel was in this case.

**Comment by Belphemur** [comment]
I choose that toolset because of this blog post on microsoft website:
https://blogs.msdn.microsoft.com/typescript/2018/08/27/typescript-and-babel-7/

My plan was to be sure people using the lib as "normal" esmodule wouldn't need to do anything to upgrade, and this seemed to be the easiest path.

**Comment by mterrel** [comment]
Thanks for the info! And thanks for being so responsive and willing to incorporate my feedback! 😃
