### ISSUE TITLE
Concurent apps locking issues

### ISSUE THREAD

**Issue by JStyle21** [Belphemur/node-json-db#566]
Hi,

I know this is a simple db model and not a real db and i've seen that you have implemented concurrency and lock support in the last few version, i've tried running 2 node apps and got the following `at async lock.writelock`.

Is it possible to have 2 node apps using the same db file? or is that not well supported yet?
Should i switch to a real db to handle this situation?

Any advice is welcome :)

**Comment by Belphemur** [comment]
Hello,

The way the lock work is by storing it in memory. So this only work for one process accessing the "db". It's there to avoid corruption of the database when concurrent access are done from the same process only. And also for only very small database as the whole DB is loaded in memory.

The use case of multiprocess accessing the same file won't be supported as for this I strongly recommend using a proper database like Postgres, SQLite or Mango depending on the needs.

**Comment by JStyle21** [comment]
Alright, figured as much.
Thanks a lot for your help.
