### ISSUE TITLE
Return undefined or null if an item was not found

### ISSUE THREAD

**Issue by ipalfy** [Belphemur/node-json-db#582]
By the way: This is a much needed and amazing library.

I will use it to create openAPI-Specification „on the fly“, by intercepting all requests in an express middleware and turning these into an openAPI document just by using the api.

Unfortunately my code is full of try/catch, since I have to check if a path/operation entry already exists. A simple check for „false“ would greatly improve my code.

**Comment by Belphemur** [comment]
Hey,

Sorry that I took so long to answer.

This is a great idea, I plan to add a `default` parameter to the get method so you can choose what to return if it's not found :)
