### ISSUE TITLE
Get an object in array by value

### ISSUE THREAD

**Issue by fransyozef** [Belphemur/node-json-db#586]
So I have an array with objects. Each object has an id. Is it possible to use the datapath to get the object with id?. 

for example

```
{
	"items": [{
		"title": "item 1",
		"id": 1
	}, {
		"title": "item2",
		"id": 2
	}]
}
```

Now I could get all items then parse through to get item with id 2 for example.
But is this something I can already do in this package?

**Comment by Belphemur** [comment]
Hello,
You can use the `find` method for that.
First parameter is the path to the array `/items` and the second the callback you want to run to find the object with the wanted id.
