### ISSUE TITLE
Request to Open Pull Request Permission for Repository

### ISSUE THREAD

**Issue by anjeongkyun** [Belphemur/node-json-db#587]
Dear [Belphemur],

I am an avid contributor to open source projects, and I have been following your repository for some time now. Recently, I came across an issue in your project that I believe I can help resolve. However, I have noticed that the pull request permission has not been opened in the issue.

I understand that asking for permission to open a pull request in the issue is a standard practice in many open source projects, but I couldn't find the option in the issue. Therefore, I would like to respectfully request that you open the pull request permission for this issue so that I can contribute to the project.

I have reviewed your contribution guidelines, and I believe that my proposed changes would be valuable to the project. If you could grant me permission to open a pull request, I would be happy to share my proposed changes with you and the rest of the community.

Thank you for your time and consideration. I look forward to hearing from you soon.

**Comment by Belphemur** [comment]
Hi @anjeongkyun,

I'm more than happy to accept contributions.

Which issue did you have in mind ?
