### ISSUE TITLE
hope to add an export method

### ISSUE THREAD

**Issue by XuMinhui** [Belphemur/node-json-db#594]
I have been using your tool library, which helped me very much. I hope to add an export method in the future, combined with node-xlsx, to export the data in the database to .xlsx, you know, for colleagues who do not know how to code, xlsx they need very much. But based on the purity of the code tool, it may make more sense to create a new accessories repository open source. I'm going to do this when I have time

**Comment by Belphemur** [comment]
Hello,

I think it would make more sense to be its own library since the export part wouldn't be one of the use case I'd like to support.
