### ISSUE TITLE
NestJS integration

### ISSUE THREAD

**Issue by ShinDarth** [Belphemur/node-json-db#62]
hello, is there an integration with [NestJS](https://github.com/nestjs/nest) for this tool?

**Comment by Belphemur** [comment]
JsonDB is a basic JS lib meant to work with NodeJS.

NestJS is simply a JS framework built on top of NodeJS.

JsonDB should work without problems with NestJS.

Simply add the lib to your NestJS project as you would do with any other libraries :)
