### ISSUE TITLE
More resilient `load()`?

### ISSUE THREAD

**Issue by iyerusad** [Belphemur/node-json-db#634]
Current implementation tries once and errors out.
https://github.com/Belphemur/node-json-db/blob/ccfabaf78695e18487ae1e5512762948518e7e18/src/JsonDB.ts#L388-L398

Since this is dealing with some idiosyncrasies around filesystems or similar, it might worth doing a simple retry ~50ms later (or even random between 50-150ms) - the current state is maintained but higher probability of success from sleep+retry when some issue encountered.

**example:**
```js
    public async load(): Promise<void> {
        if (this.loaded) {
            return
        }
        try {
            this.data = await this.config.adapter.readAsync();
            this.loaded = true
        } catch (err) {
            try {
                await new Promise(r => setTimeout(r, 50));
                this.data = await this.config.adapter.readAsync();
                this.loaded = true
            } catch (err) {
                throw new DatabaseError("Can't Load Database", 1, err)
            }
        }
    }
```

**Comment by Belphemur** [comment]
Hello,

If there are issues with the Filesystem, I rather let the developer using the lib be in control of any retry logic. Moreover, the adapter can be replaced by any other that implement the contract.
