### ISSUE TITLE
Feature request:DB file saving path

### ISSUE THREAD

**Issue by Mero-Plaform** [Belphemur/node-json-db#644]
I didn't find any mentions about build in possibility to set DB file saving path

Hope you will add this feature, purhaps as Config para, or as a part of DB name

Storing the file at the root of the project messes up the files structure a bit

**Comment by Belphemur** [comment]
Hello,

The first parameter of the Config is the path to the file. You can choose to set it anywhere you see fit.

**Comment by Mero-Plaform** [comment]
Yes, that's work, thank you

But I highly recommend you to provie this info you gave me right in to the "Usage" page

The place, where you describe "The first argument is the database"
