### ISSUE TITLE
In DEV env 'node-json-db' is not loading

### ISSUE THREAD

**Issue by mrasal** [Belphemur/node-json-db#65]
In the app we are using React, ElectronJS and webpack 2. when we use 'node-json-db' in electronConfig file then in DEV env it is giving "Cannot find module 'node-json-db'" error, But in PROD env it is working fine.

don't know what is wrong in DEV env.

**Comment by Belphemur** [comment]
I'm sorry you're using a old version of webpack, I can't really help ...
