### ISSUE TITLE
Read/Write lock

### ISSUE THREAD

**Issue by colinbes** [Belphemur/node-json-db#798]
I am at a loss on how to provide atomic operations - I see use of read/write async locks but can't figure out how to use them.

I am wanting to provide atomic increment of a value in json element which.

get current counter, increment counter, save counter.

Can you please point me in the right direction.

Thanks for all your work

**Comment by Belphemur** [comment]
Hello,

That is handled by the library. You don't have to do anything to be able to use concurrent operations.

However, for anything critical, I'd always suggest to use a real database ^^

**Comment by colinbes** [comment]
I did see all the locking implemented in library but there is no way that I can see to ensure atomic operation that covers a read and then a write. To me it looks like the atomic operation is either over a read or a write. If I call read as per library to retrieve my count value and then if I get a write to this db before I fire off an increment and then write I’d end up with corrupted data. I’m looking to doStart lock -> read data -> manipulate data -> commit changed data in one atomic operation. I don’t see how this is possible with current libraries unless I am misunderstanding something. In the lock library you’re using the mention upgrading from read to write lock. Thanks for responding!Sent from my iPhoneOn Mar 29, 2024, at 16:28, Antoine Aflalo ***@***.***> wrote:﻿
Hello,
That is handled by the library. You don't have to do anything to be able to use concurrent operations.
However, for anything critical, I'd always suggest to use a real database ^^

**Comment by Belphemur** [comment]
Basically the lib I'm using only lock on write.
So you don't need to manage manually the atomic operation.

The concept is: if there is a write happening, the full db is locked until it finishes.
If there is a read happening, the db will block any write until the read finishes, but will let any concurrent read continue.

This is to avoid the JSON file to be corrupted, since by default any write will rewrite the json file.

**Comment by colinbes** [comment]
Thanks
