### ISSUE TITLE
Slightly curious with this

### ISSUE THREAD

**Issue by LordYusei** [Belphemur/node-json-db#8]
Okay, so I'm using a project that included this as a basic json library. What i'm trying to do is create a part of the database with data for a gamemode. The data will include HP, level, exp, weapon and the username. How would I do this? I know it's a nooby question but i'm coming from Python where I used json.dumps and json.loads for this. Thanks if anyone can help me :P

**Comment by Belphemur** [comment]
It really depends exactly what you want to do. If you want to set up a template like basic HP, level for monster etc ... or you want to use it to save the state of a player.

Keep in mind, this "database library" is really not made for doing a lot of change in the same time, I created it to simplify the use of json files.

What I would do is create a Player Object with all those different properties then save in the database using push at the point */players/[PLAYER_NAME]* that object. Where [PLAYER_NAME] would be the unique name of the player (username).

Like this you would be able later to retrieve it directly (**getData(*/players/[PLAYER_NAME]*)**) and do what you must with it.

**Comment by LordYusei** [comment]
I see. So I would do something like db.push('/players/player.name') and then define each area, right?

**Comment by Belphemur** [comment]
either that if you're setting the whole object but you can also set each part separatly:

db.push('/players/player.name/hp', 10)
db.push('/players/player.name/exp', 100)

etc...

when you'll do a db:getData('/players/player.name') you'll get an object containing hp and exp.

There are a lot of examples in the test scripts

**Comment by LordYusei** [comment]
Oh I see. Thanks so much for the help. :)

**Comment by Belphemur** [comment]
I close this for now. Don't hesitate to reopen it if you have further questions.
