### ISSUE TITLE
 cant find the meaning for the argument in db.push function

### ISSUE THREAD

**Issue by wz30** [Belphemur/node-json-db#81]
db.push("/arraytest/myarray[]/myTest", 'test', true);
What is the point for the last argument true?  I can not find it in reademe

**Comment by Belphemur** [comment]
Hello,

When using the Lib your IDE is supposed to pull the methods documentation.
https://github.com/Belphemur/node-json-db/blob/develop/src/JsonDB.ts#L209-L215

As you can see the last parameter let you either override any existing data at that key, or attempt to merge the new data with the existing one.

**Comment by wz30** [comment]
Cool, thanks a lot!
