### ISSUE TITLE
Do I need to await db.save() after each push, as documented?

### ISSUE THREAD

**Issue by jfoclpf** [Belphemur/node-json-db#825]
Do I need to `await db.save()` after _each_ push, as documented?

Or can I simply do it once at the end of several pushes to improve performance?

```js
var db = new JsonDB(new Config("myDataBase", false, false, '/'));

await db.push("/test1","super test")
await db.push("/test2/my/test",5)
await db.save()
```

It's not clear in documentation

**Comment by Belphemur** [comment]
Hello,

In the example code you've written, it won't save automatically at every push and only when you manually call save.
It is a totally valid use case. Just keeping in mind, if the application get interrupted or crash before the save is called, the data in the file won't be up-to-date.
