### ISSUE TITLE
Error: Cannot find module 'node-json-db/dist/types/lib/JsonDBConfig' on typescript 3.5.1

### ISSUE THREAD

**Issue by lucacalcaterra** [Belphemur/node-json-db#85]
What's wrong ? 

I've installed npm as readme but at runtime i got this error.

Thanks !

**Comment by torbensky** [comment]
Also ran into this issue. Library setup doesn't seem to work well with a simple TS project that follows example code.

**Comment by lDisciple** [comment]
What was the solution to this as I also have this error

**Comment by Belphemur** [comment]
I've repackaged the lib.


Can you tried with the 1.0.0?


________________________________

**Comment by Vandesm14** [comment]
I am getting the same error. The package is up to date (v1.0.0). I have also tried running my js file in experimental mode, which clears up the import errors, but fails to get the "node-json-db/lib/JsonDBConfig".
![nodedbjsonerror](https://user-images.githubusercontent.com/23623276/61386841-fddf5e80-a882-11e9-97cf-a66a818971a4.PNG)

**Comment by Belphemur** [comment]
@Vandesm14 & @lucacalcaterra & @torbensky & @lDisciple 

To fix the problem, I updated the readme:

```js
import { Config } from 'node-json-db/dist/lib/JsonDBConfig'
```
