### ISSUE TITLE
How to Fetch a Key Value from Array

### ISSUE THREAD

**Issue by burhanahmed92** [Belphemur/node-json-db#88]
My Json Array:
`{"paths":[{"id":74185, "name": "John"}, {"id":54874, "name": "Clark"}]}`

How can i fetch and puch where id is equal to 74185. 
I am trying like this:
` var data = db.getData("/paths/id/74185");`

But not working. Kindly guide me

**Comment by Belphemur** [comment]
Hello,

Seeing your use case I would advise to use the find method: https://belphemur.github.io/node-json-db/classes/jsondb.html#find

```js
const search = 74185
const data = db.find("/paths", (entry) => {
   return entry.id == search
})
```
