### ISSUE TITLE
how to use with nodejs

### ISSUE THREAD

**Issue by dvargas135** [Belphemur/node-json-db#90]
how do i use require() instead of import

**Comment by dvargas135** [comment]
getting TypeError: Config is not a constructor

`var JsonDB = require('node-json-db');
var Config = require('node-json-db/dist/lib/JsonDBConfig');

var db = new JsonDB(new Config("warns.json", true, false, '.'));`

**Comment by Belphemur** [comment]
You need to take/deconstruct the exact object, not the full exported one.

```js
const JsonDB = require('node-json-db').JsonDB;
const Config = require('node-json-db/dist/lib/JsonDBConfig').Config;

var db = new JsonDB(new Config("myDataBase", true, false, '/'));
```

**Comment by dvargas135** [comment]
ah, my bad thank you man

**Comment by AndrejGajdos** [comment]
> ```js
> JsonDB
> ```

Would be nice to add this into README

**Comment by Belphemur** [comment]
ESM `import` has been available since nodejs 12 which is the latest LTS.

If you're using anything older than 12, I'd advise to update your version of nodejs.

Nonetheless, I'll add a small section about nodejs 10.

**Comment by AndrejGajdos** [comment]
Good to know. I thought it is still an "experimental feature".

**Comment by Creative-Difficulty** [comment]
> ESM `import` has been available since nodejs 12 which is the latest LTS.
> 
> If you're using anything older than 12, I'd advise to update your version of nodejs.
> 
> Nonetheless, I'll add a small section about nodejs 10.

And how do I use your answer with the import syntax?

**Comment by Creative-Difficulty** [comment]
> You need to take/deconstruct the exact object, not the full exported one.
> 
> ```js
> const JsonDB = require('node-json-db').JsonDB;
> const Config = require('node-json-db/dist/lib/JsonDBConfig').Config;
> 
> var db = new JsonDB(new Config("myDataBase", true, false, '/'));
> ```

Doesn't even work lol
