### ISSUE TITLE
Error when the path contains the dot char

### ISSUE THREAD

**Issue by antoniofarina** [Belphemur/node-json-db#95]
When the path contains the dot, the append to array function has an unexpected behaviour

For example, givin the structure 
```
{  
   "site":{  
      "content":{  
         "it":{  
            "about-us.md":[]
         }
      }
   }
}
```

the instruction 
``` 
db.push ("/site/content/it/about-us.md[]", {"code":0, "value": 1}) 
``` 

result in 
```
{  
   "site":{  
      "content":{  
         "it":{  
            "about-us.md":[],
             "about-us.md[]" : {"code":0, "value": 1}
         }
      }
   }
}
```

instead of 
```
{  
   "site":{  
      "content":{  
         "it":{  
            "about-us.md":[ {"code":0, "value": 1}]
         }
      }
   }
}
```

**Comment by 5imun** [comment]
Also the same thing happens when first character in array name is digit (example: name '11_Dec_2019' doesn't work but 'Dec_11_2019' works):
Instructions:
```
database.push(`/request_errors/11_Dec_2019[]`, {test:1});
  database.push(`/request_errors/11-feb_19[]`, {test:1});
  database.push(`/request_errors/1111_[]`, {test:1});
  database.push(`/request_errors/11_11[]`, {test:1});
  database.push(`/request_errors/d.s_12-[]`, {test:1});
  database.push(`/request_errors/d.s_-[]`, {test:1});
  database.push(`/request_errors/_d.s-[]`, {test:1});
  database.push(`/request_errors/Dec_11_2019[]`, {test:1});
  database.push(`/request_errors/11sd11_[]`, {test:1});
  database.push(`/request_errors/feb_11[]`, {test:1});
  database.push(`/request_errors/_1111[]`, {test:1});
  database.push(`/request_errors/sd-11[]`, {test:1});
  database.push(`/request_errors/d-11-[]`, {test:1});
  database.push(`/request_errors/d_11-[]`, {test:1});
```
Result:
```
{
    "request_errors": {
      "11_Dec_2019[]": {"test": 1},
      "11-feb_19[]": {"test": 1},
      "1111_[]": {"test": 1},
      "11_11[]": {"test": 1},
      "d.s_12-[]": {"test": 1},
      "d.s_-[]": {"test": 1},
      "_d.s-[]": {"test": 1},
      "11sd11_[]": {"test": 1},
      "Dec_11_2019": [
        {"test": 1}
      ],
      "feb_11": [
        {"test": 1}
      ],
      "_1111": [
        {"test": 1}
      ],
      "sd-11": [
        {"test": 1}
      ],
      "d-11-": [
        {"test": 1}
      ],
      "d_11-": [
        {"test": 1}
      ]
    }
  }
```
I would suggest checking if name [valid variable name](https://mathiasbynens.be/notes/javascript-identifiers);

> An identifier must start with $, _, or any character in the Unicode categories “Uppercase letter (Lu)”, “Lowercase letter (Ll)”, “Titlecase letter (Lt)”, “Modifier letter (Lm)”, “Other letter (Lo)”, or “Letter number (Nl)”.

> The rest of the string can contain the same characters, plus any U+200C zero width non-joiner characters, U+200D zero width joiner characters, and characters in the Unicode categories “Non-spacing mark (Mn)”, “Spacing combining mark (Mc)”, “Decimal digit number (Nd)”, or “Connector punctuation (Pc)”.

So name should not start with the digit character (number) and it should not contain dots.
It is weird that it is working properly with names containing - (minus)

**Comment by antoniofarina** [comment]
> So name should not start with the digit character (number) and it should not contain dots.
> It is weird that it is working properly with names containing - (minus)

I do not agree. JSON is a representation of a data structure and it is agnostic to the data structure semantic. Moreover, Json allows that a key (that is a string) contains a dot or start with a number.

```
let a={}
a['test.txt']= {}
a['test.txt']={"type":"file","kb":"2134"}
console.log(JSON.stringify(a))
> {"test.txt":{"type":"file","kn":2134}}
```

**Comment by 5imun** [comment]
Yea you are right but i always expect that i can access property of object without square brackets i don't think that you can do that if your variable name is not valid. Anyway i just wanted to notify you that this error also happens when you use number at the start of the array name, i really like the packet by the way.

**Comment by Belphemur** [comment]
That is really interesting bug, it means my regex that detect the "array" isn't working as intended.

It's a bug, not a decision I made :)
I'll see if I can fix it.
