### ISSUE TITLE
How to configure json file save location?

### ISSUE THREAD

**Issue by adame21** [Belphemur/node-json-db#96]
Hi,

Just started using this package and its great and makes life much easier so thanks for that.

Just one small question, can I configure where I want my JSON file to be saved in my project? like give it some path or something?

Thanks!

**Comment by Belphemur** [comment]
Hello 👋

If you check the generated documentation you'll see you can set it in the configuration object ;) 

Set either a full or relative path to the file where you want it to be stored. 
________________________________

**Comment by adame21** [comment]
Hello,

Yeah that works absolutely perfect - just added relative path to the db name upon creating it.

Thanks! great package, made my life so much easier.
