### ISSUE TITLE
db.delete can't delete objects in array based on index if the array name contains dashes

### ISSUE THREAD

**Issue by fortlaxjoel** [Belphemur/node-json-db#98]
For example:

`db.delete("/arraytest/my-array[0]"); // Wont work`
`db.delete("/arraytest/myarray[0]"); // Will work`

I am storing an SSID as the array name and it would greatly simplify the code if i could keep it that way. Otherwise i will have to loop the array, match the SSID value, check the index of that value and delete the subdata based on the index where it matched the SSID value.

I have tried to encase the array name in brackets, to no avail.

Interestingly

`db.delete("/arraytest/my-array"); // Will work just fine.`

Anyone know a way to fix this?
Thanks for a great plugin.

**Comment by Belphemur** [comment]
Dash isn't currently supported in array name.

Will be fixed in next release.
